# ==> Create schemas in Database
- name: password file for schema creation
  template: src=passwords.txt dest={{ mw_installer_folder }} owner={{ mw_user }} group={{ mw_group }}
- name: copy create schema script
  template: src=create_schema.sh dest={{ mw_installer_folder }} owner={{ mw_user }} group={{ mw_group }} mode=0755
- name: run create schema script
  shell: "{{ mw_installer_folder }}/create_schema.sh"
 
# ==> Create new domain
- name: copy create domain python script
  template: src=create-domain.py dest={{ mw_installer_folder }} owner={{ mw_user }} group={{ mw_group }}

- name: rename the domain template jar
  command: "sed -i.bak 's/mw.em_wls_template_12.1.3.jar/mw.em_wls_template.jar/' {{ mw_installer_folder }}/create-domain.py"

- name: Execute create domain script
  shell: "{{ weblogic_home }}/common/bin/wlst.sh {{ mw_installer_folder }}/create-domain.py"
  sudo_user: '{{ mw_user }}'
 
# ==> Start nodemanager
- name: Create security directoy to Nodemanager Home
  file: state=directory path={{ nodemanager_home }}/security owner={{ mw_user }} group={{ mw_group }}
  sudo_user: '{{ mw_user }}'
- name: Copy Nodemanager Properties file
  template: src=nodemanager.properties dest={{ nodemanager_home }}/ owner={{ mw_user }} group={{ mw_group }}
- name: Waiting for nodemanager to come up
  wait_for: port=5556 delay=2 timeout=30
 
# ==> Start AdminServer
- name: Create security folder on Admin Server
  file: state=directory path={{ domains_home }}/{{ domain_name }}/servers/{{ admin_server_name }}/security owner={{ mw_user }} group={{ mw_group }}
- name: Create boot.properties file
  template: src=boot.properties dest={{ domains_home }}/{{ domain_name }}/servers/{{ admin_server_name }}/security/ owner={{ mw_user }} group={{ mw_group }}
- name: Copy Admin Server start-up script
  template: src=start-admin-server.py dest={{ mw_installer_folder }} owner={{ mw_user }} group={{ mw_group }} mode=0755
- name: Execute start Admin Server script
  shell: "{{ weblogic_home }}/common/bin/wlst.sh {{ mw_installer_folder }}/start-admin-server.py"
  sudo_user: '{{ mw_user }}'
- name: Wait for Admin Server to startup
  wait_for: port={{ admin_server_port }} delay=2 timeout=60
 
