- name: Configure linux with jdk
  hosts: weblogic
  sudo: true
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
    - keys.yml
  # ==> Configure Linux
- name: Install required libraries
  yum: name={{ item }} state=present
  with_items: "{{ packages_list }}"
- name: Disable SELinux
  selinux: state=disabled
- name: Disable Firewall Deamon (firewalld)
  service: name=firewalld state=stopped enabled=no
- name: Change kernel parameters
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: "{{ kernel_params }}"
- name: Create MW Home directory
  file: state=directory path={{ middleware_home }} owner={{ mw_user }} group={{ mw_group }}
- name: Create Domain Home directory
  file: state=directory path={{ domains_home }} owner={{ mw_user }} group={{ mw_group }}
- name: Create Apps Home directory
  file: state=directory path={{ applications_home }} owner={{ mw_user }} group={{ mw_group }} 

- name: Get the jdk binaries
  maven_artifact:
    group_id: com.setup
    artifact_id: jdk1.8
    repository_url: 'http://10.0.3.11:8081/repository/jdk/1.8/jdk-8u181-linux-x64.tar.gz'
    username: uname
    password: pass
    dest: /tmp/jdk-8u181-linux-x64.tar.gz

- name: Get the fmw binaries
  maven_artifact:
    group_id: com.setup
    artifact_id: wls_infra
    repository_url: 'http://10.0.3.11:8081/repository/wls/12c/fmw_12.2.1.3.0_infrastructure.jar'
    username: uname
    password: pass
    dest: /tmp/fmw_12.2.1.3.0_infrastructure.jar


- name: Extract JDK archive
  command: 'tar -xvf /tmp/{{ jdk_installation_archive }} -C {{ mw_home }}'
  args:
    creates: "{{ jdk_folder }}"
- name: Change ownership of jdk folder
  file: path="{{ jdk_folder }}" owner={{ mw_user }} group={{ mw_group }} recurse=yes
- name: Change entropy device for java
  command: "sed -i.bak 's/urandom/.\\/urandom/' {{ jdk_folder }}/jre/lib/security/java.security"
- name: Add JAVA_HOME environment variariables in bashrc
  lineinfile: dest='/home/{{ mw_user }}/.bashrc' line='export JAVA_HOME={{ jdk_folder }}'
- name: Add Java bin folder to path in bashrc
  lineinfile: dest='/home/{{ mw_user }}/.bashrc' line='export PATH=$PATH:$JAVA_HOME/bin'
  
- name: Configure WebLogic 12c domain
  hosts: weblogic
  become: yes
  become_user: "{{ mw_user }}"
  vars_files:
    - vars/main.yml
    - secrets.yml
  tasks:
    - task: wls-install.yml
    - task: domain-config.yml
    - task: wls-managed.yml
    