# ==> Install wls
- name: Create installer directory
  file: state=directory path={{ mw_installer_folder }} owner={{ mw_user }} group={{ mw_group }}

- name: Copy Middleware Installer
  command: "cp /tmp/{{ mw_installer }} {{ mw_installer_folder }}"
- name: Copy file for silent installation
  template: src=silent-weblogic.txt dest={{ mw_installer_folder }} owner={{ mw_user }} group={{ mw_group }}

- name: Change the permission of the tmp dir 
  command: 'chmod -R 777 /tmp'
  become_user: root

- name: Copy OraInst.loc
  template: src=oraInst.loc dest={{ mw_installer_folder }} owner={{ mw_user }} group={{ mw_group }}
#- name: change the permission of tmp dir
#  command: "chmod -R 755 /tmp/"
- name: execute Weblogic installer
  command: "{{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m -jar {{ mw_installer_folder }}/{{ mw_installer }} mw_HOME=/mw/fmw12.1.3/product/mwHome -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"
  sudo_user: '{{ mw_user }}'